[package]
    name    = "discord-bot"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    log = "0.4.29"
    poise = "0.6.1"
    tokio = { version = "1.49.0", features = [
        "rt-multi-thread",
    ] }
    tracing-subscriber = "0.3.22"
